### ISSUE TITLE
747-400 - Delta or United

### ISSUE THREAD

**Issue by chooeybooey** [geofs-plugins/aircraft-warehouse#25]
**The model I want**: 747-400

**The livery I want**: Delta or United

**Special reason for desiring this aircraft**: This huge beast is amazing to fly!

**Enter some pictures of a real-life aircraft here**:
![image](https://user-images.githubusercontent.com/31420396/29792033-b87d97f4-8c04-11e7-90db-ac942a818710.png)
![image](https://user-images.githubusercontent.com/31420396/29792077-dac31712-8c04-11e7-8803-ee818085f1d4.png)

**Comment by Featherway** [comment]
The game needs a 747 because there is none. But Delta would be amazing, AMAZING!
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwiwttO_6frVAhXFRiYKHY1uB_0QjRwIBw&url=http%3A%2F%2Fflyingwithfish.boardingarea.com%2F2008%2F12%2F17%2Fdelta-airlines-747-400-takes-to-the-sky-the-first-sign-of-the-delta-northwest-merger%2F&psig=AFQjCNHlu2vVz2Y62QaMaAukoD_sETqvbw&ust=1504040450874173

**Comment by Featherway** [comment]
The game needs a 747 because there is no 747. But Delta would be amazing, AMAZING!
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwiwttO_6frVAhXFRiYKHY1uB_0QjRwIBw&url=http%3A%2F%2Fflyingwithfish.boardingarea.com%2F2008%2F12%2F17%2Fdelta-airlines-747-400-takes-to-the-sky-the-first-sign-of-the-delta-northwest-merger%2F&psig=AFQjCNHlu2vVz2Y62QaMaAukoD_sETqvbw&ust=1504040450874173
